queue_rules:
  - name: default

    queue_conditions:
      - base=main
      - author=dependabot[bot]
      - status-success=CI
      - status-success=Docker E2E Tests
      - status-success=Kubernetes E2E Tests
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    merge_conditions: []
    merge_method: squash
